travis:
  secure:
    BINSTAR_TOKEN: RW37/8tZ4ZxD2FL/Z8hWf/9O83DIl2DIL/OZErWeVWbCyf3uhgWi6ss2gO0Xt1qHU1X8xpGrL2Si9vDtzV7WYUCNk+RMyvi50AmrQH3rzWzAmEpj/is00RNaVOE8rDML3uHoZZwKYE60cyynmRfNud02W0EzTW7hjTRKc76Qw8OL1BPQlFPrROuz8EM6IVcxVZz8QTuGtBriUw7s4egVUFyYLztESkdOBH7EDF+C9/KPH2oea8nuQYP9RpZGOLvEeNCwhqOCfNAqF4oCixxRxGdlDw7ljjBNckyd7Iw8Ge2Y4cMPfqDmHnYWTTY5OEa2zZt12a+XF9Mz89z0IJ3CwHlJTfKmU61bUjjsNW9PrkIViTpx0hPLkgM6t8BmnLmeWmO4/RgEFi3NprfVMv9/uuuSp8AHjEYL8nRg7v0qb3oB7DKlsirPmUAyXWK8BfAgQKhlgHCgh8pzAzb5sH0Bex+uYFQ0i9w8UIXrwGewnuWWpDWJa8P9acIMB8N3kmpTCcgcLSjkd7FZYatJ7w72RTbhpxh5eqKALM7r7iAwun8j9y+95n6AbVIW9P83P4p6LNzRTGTPnH7BaVaoNmWsawSe7jyS4NlwyjazrakYXcUbcBMN4o1l6yZCvNrBMJcNmw4Dy1T2G+PZa9Kmm8CUkeqZOonmaCoFc7LaASUtrpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
